### ISSUE TITLE
有没有可能实现扫描连接

### ISSUE THREAD

**Issue by UknowHui** [remoboard/remoboard.github.io#1]

**Comment by everettjf** [comment]
新版本支持Web输入模式了。

老版本的IP输入模式不考虑继续投入时间了。

看看这几篇文章哈

- [少数派:「远程输入法」新版发布，用浏览器给手机打字]( https://sspai.com/post/57008)
- [异次元: 远程输入法 - 用电脑键盘给手机打字的创意效率应用！省蓝牙键盘钱了](https://www.iplaysoft.com/remoboard.html)
- [最美应用: 这款 APP 终于解决了困扰我这么多年的麻烦](https://mp.weixin.qq.com/s/PLWkVuEdJCk6cLGEQVZDbw)
