### ISSUE TITLE
无法启动此程序，因为计算机中丢失 api- ms-win-core-winrt-string-l1-1-0. dll。尝试重新安装该程序以解决此问题

### ISSUE THREAD

**Issue by 732351184** [remoboard/remoboard.github.io#2]
![新建位图图像](https://user-images.githubusercontent.com/30804718/64769347-b7a23500-d57d-11e9-8254-8694e0b7d9bb.jpg)
重装了几次还是打不开

**Comment by everettjf** [comment]
参考这几篇文章哈。不再需要安装电脑客户端了。

- [少数派:「远程输入法」新版发布，用浏览器给手机打字]( https://sspai.com/post/57008)
- [异次元: 远程输入法 - 用电脑键盘给手机打字的创意效率应用！省蓝牙键盘钱了](https://www.iplaysoft.com/remoboard.html)
- [最美应用: 这款 APP 终于解决了困扰我这么多年的麻烦](https://mp.weixin.qq.com/s/PLWkVuEdJCk6cLGEQVZDbw)
