### ISSUE TITLE
iOS + macOS 连接失败

### ISSUE THREAD

**Issue by AlphaWang** [remoboard/remoboard.github.io#3]
通过IP方式连接，macOS端一直提示connecting ，最后连接失败

**Comment by everettjf** [comment]
谢谢使用，很抱歉，应用刚发布，现在在某些网络下兼容性不好，原因还在调查中，可以先试试蓝牙连接方式。

________________________________
发件人: Alpha <notifications@github.com>
发送时间: 2019年9月15日 15:20
收件人: remoboard/remoboard.github.io <remoboard.github.io@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [remoboard/remoboard.github.io] iOS + macOS 连接失败 (#3)


通过IP方式连接，macOS端一直提示connecting ，最后连接失败

―

**Comment by idonen** [comment]
ios稳定的连接可以参考一下。
https://github.com/libimobiledevice/usbmuxd

**Comment by everettjf** [comment]
十分感谢，这个就需要连接usb线了。确实可以作为补充。
________________________________

**Comment by idonen** [comment]
一边充着电，一边通过quicktime或者ios-minicap（https://github.com/openstf/ios-minicap）把手机屏幕映射到Mac上，再一边打着字，岂不更爽。

**Comment by everettjf** [comment]
可以先试试我的另一个应用，USBKeyboard，能搜到，只是收费哈

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: idonen <notifications@github.com>
发送时间: Monday, September 16, 2019 9:00:41 PM
收件人: remoboard/remoboard.github.io <remoboard.github.io@noreply.github.com>
抄送: everettjf <everettjf@live.com>; Comment <comment@noreply.github.com>
主题: Re: [remoboard/remoboard.github.io] iOS + macOS 连接失败 (#3)


一边充着电，一边通过quicktime或者ios-minicap（https://github.com/openstf/ios-minicap）把手机屏幕映射到Mac上，再一边打着字，岂不更爽。<https://github.com/openstf/ios-minicap%EF%BC%89%E6%8A%8A%E6%89%8B%E6%9C%BA%E5%B1%8F%E5%B9%95%E6%98%A0%E5%B0%84%E5%88%B0Mac%E4%B8%8A%EF%BC%8C%E5%86%8D%E4%B8%80%E8%BE%B9%E6%89%93%E7%9D%80%E5%AD%97%EF%BC%8C%E5%B2%82%E4%B8%8D%E6%9B%B4%E7%88%BD%E3%80%82>

―

**Comment by AlphaWang** [comment]
谢谢各位的回复，USBKeyboard 使用正常！支持下作者~

**Comment by everettjf** [comment]
感谢😊看来未来需要把USBKeyboard集成到远程输入法中
________________________________
