### ISSUE TITLE
win7 x64 旗舰版无法运行软件

### ISSUE THREAD

**Issue by txdier** [remoboard/remoboard.github.io#4]
![image](https://user-images.githubusercontent.com/30993382/67560106-c66b3280-f74c-11e9-8af7-f09055f1cfb9.png)

输入法版本1.3
系统版本：windows 7 x64 旗舰版 Serivce Pack 1

**Comment by everettjf** [comment]
你好，推荐看新的文章哈


「最美应用」写了一篇介绍「远程输入法」的文章，写的真好。更加通俗易懂，还易用传播。
文章地址是：https://mp.weixin.qq.com/s/PLWkVuEdJCk6cLGEQVZDbw
大家可以对比我之前在「少数派」写的文章 https://sspai.com/post/57008
同一个应用的宣传，不同的写法。

也可以加我微信 everettjf

________________________________
发件人: Q <notifications@github.com>
发送时间: Friday, October 25, 2019 5:28:57 PM
收件人: remoboard/remoboard.github.io <remoboard.github.io@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [remoboard/remoboard.github.io] win7 x64 旗舰版无法运行软件 (#4)


[image]<https://user-images.githubusercontent.com/30993382/67560106-c66b3280-f74c-11e9-8af7-f09055f1cfb9.png>

输入法版本1.3
系统版本：windows 7 x64 旗舰版 Serivce Pack 1

―

**Comment by everettjf** [comment]
@txdier 故意加了限制～只支持win10了。
